version: '3.9'

services:
  api:
    build: .
    restart: always
    container_name: 'agility_api'
    ports:
      - '3333:3333'
      - '9229:9229'
    command: sh ./docker-entrypoint.sh
    volumes:
      - .:/usr/app/
    depends_on:
      - 'postgres'
      - 'redis'
    environment:
      DB_HOST: 'postgres'
      REDIS_HOST: 'redis'

  postgres:
    image: 'postgres:13-alpine'
    restart: always
    container_name: 'postgres'
    volumes:
      - db-data:/db/postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

  redis:
    image: 'redis:6'
    restart: always
    container_name: 'redis'
    volumes:
      - db-data:/db/redis
    ports:
      - '6379:6379'

volumes:
  db-data:
